views/login.py
from flask import render_template, Blueprint, request, url_for, flash, redirect, request, session
from models import Users
from models import db, bcrypt
from views.forms import RegistrationForm, LoginForm
from flask_login import login_user, current_user, logout_user, login_required

auth = Blueprint('auth', __name__, template_folder='templates')

"""@login.route('/new', methods=['POST', 'GET'])
def createAccount():
    if request.method == "POST":
        firstName = request.form.get('FirstName')
        lastName = request.form.get('LastName')
        email = request.form.get('Email')
        password = request.form.get('Password')
        username = request.form.get('Username')
        user = Users(firstName, lastName, email, username, password)
        db.session.add(user)
        db.session.commit()
    return render_template("registration.html")
"""

@auth.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        #user = Users(firstName, lastName, email, username, password)
        user = Users(firstName=form.firstname.data, lastName=form.lastname.data, email=form.email.data, username=form.username.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        #session['logged_in'] = True

        return redirect(url_for('auth.login',messages=''))
    return render_template('registration.html', title='Register', form=form)


@auth.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = LoginForm()
    if form.validate_on_submit():

        user = Users.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args['messages'] 
            #next_page = request.args.get("next")
            print("*************")
            print(next_page)
            session['logged_in'] = True
            return redirect(next_page) if next_page=="/predict" else redirect(url_for('home'))

            #flash('Login successful.', 'success')
            #if next_page=="/predict":
            #    return redirect(next_page) 
            #else:               
            #    redirect(url_for('home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
            return redirect(url_for('auth.redirected'))
    return render_template('login.html', title='Login', form=form)

@auth.route("/redirected", methods=['GET', 'POST'])
def redirected():
    return redirect(url_for('auth.login' , messages=''))


@auth.route("/logout")
def logout():
    logout_user()
    session['logged_in'] = False

    return redirect(url_for('home'))

views/predict.py
from flask import Flask, render_template, request, jsonify, json, Blueprint, redirect, url_for
from flask_sqlalchemy import SQLAlchemy  
from wtforms import SelectField, Form
from flask_wtf import FlaskForm
from flask_login import current_user
from views.forms import Form
from models import Region, Municipality, Emplacement
import numpy as np
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
import joblib


model=pickle.load(open('model.pkl','rb'))


sc_X = joblib.load("data_transformer.joblib") 
 
pred = Blueprint('pred', __name__, template_folder='templates')
def transf(l):
    a = [12, 19, 20, 29, 34, 44, 48,  0,  1, 13, 15, 30, 31, 33, 46, 50,  8,
        4,  6, 16, 21, 22, 23, 55,  2, 24,  5, 45, 52,  9, 35, 38, 47,  7,
       54, 36, 37, 39, 40, 42, 51, 26, 27, 28, 43, 56, 18, 25, 32, 17, 49,
        3, 14, 10, 11, 41, 53]
    l0 = [0]*59
    l0[-1], l0[-2] = l[-1], l[-2]
    l0[a[l[0]-1]-1] = 1
    return l0

         
@pred.route('/predict', methods=['GET', 'POST'])
def predict():
    if not current_user.is_authenticated:
        #print(request.path)
        return redirect(url_for('auth.login', messages=request.path))

        #return redirect(url_for('auth.login'))
    form = Form()
    form.region.choices = [(region.id, region.name) for region in Region.query.all()]
    form.region.default = '1'
    if request.method == 'POST':
        emplacement = Emplacement.query.filter_by(id=form.emplacement.data).first()
        region = Region.query.filter_by(id=form.region.data).first()
        municipality = Municipality.query.filter_by(id=form.municipality.data).first()
        area = int(form.area.data)
        roomNumber = int(form.roomNumber.data)
        emp = emplacement.id
        int_features = [emp, roomNumber, area]
        final = np.array(transf(int_features)).reshape(-1, 59)
        print("**" , final)

        final[:,57:] = sc_X.transform(final[:,57:]) 
        print("**" , final)

        prediction = model.predict(final)

        return render_template('price.html',price=round(prediction[0], 2))
    return render_template('predict.html', form=form)
 
@pred.route('/municipality/<get_municipality>')###
def municipalitybyregion(get_municipality):
    municipality = Municipality.query.filter_by(region_id=get_municipality).all()
    municipalityArray = []
    for emplacement in municipality:
        municipalityObj = {}
        municipalityObj['id'] = emplacement.id
        municipalityObj['name'] = emplacement.name
        municipalityArray.append(municipalityObj)
    return jsonify({'municipalityregion' : municipalityArray})
  
@pred.route('/emplacement/<get_emplacement>')
def emplacement(get_emplacement):
    municipality_data = Emplacement.query.filter_by(municipality_id=get_emplacement).all()
    emplacementArray = []
    for emplacement in municipality_data:
        emplacementObj = {}
        emplacementObj['id'] = emplacement.id
        emplacementObj['name'] = emplacement.name
        emplacementArray.append(emplacementObj)
    return jsonify({'emplacementlist' : emplacementArray}) 

templates/a.html
<!DOCTYPE html>
<html>

<head>

  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />


  <title>ECHRIDAR</title>

  <!-- slider stylesheet -->
  <link rel="stylesheet" type="text/css"
    href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css" />

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="static/css/bootstrap.css" />

  <link rel="stylesheet" type="text/css" href="static/css/container-image.css" />
  <!DOCTYPE html>
  <html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
 
 
 
  

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,700|Roboto:400,700&display=swap" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="static/css/style.css" rel="stylesheet" />
  <!-- responsive style -->
  <link href="static/css/responsive.css" rel="stylesheet" />
  <style>
    body, html {
      height: 100%;
      margin: 0;
      font-family: Arial, Helvetica, sans-serif;
    }
    
    * {
      box-sizing: border-box;
    }
    
    .bg-image {
      /* The image used */
      background-image: url("static/images/about-img.png");
      
      /* Add the blur effect */
      filter: blur(8px);
      -webkit-filter: blur(8px);
      
      /* Full height */
      height: 100%; 
      
      /* Center and scale the image nicely */
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
    }
    
    /* Position text in the middle of the page/image */
    .bg-text {
      background-color: #1e025b ; /* Fallback color */
      background-color:#1e025b; /* Black w/opacity/see-through */
      color: white;
      font-weight: bold;
      border: 3px solid #f1f1f1;
      position: absolute;
      top: 50%;
      left: 50%;
      transform: translate(-50%, -50%);
      z-index: 2;
      width: 80%;
      padding: 20px;
      text-align: center;
    }
    </style>
</head>
  <body>
  
    <h1 style="background-color: #1e025b; /* Fallback color */
    background-color:#1e025b; /* Black w/opacity/see-through */
    color: white;
    font-weight: bold;
    border: 3px solid #f1f1f1;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    z-index: 2;
    width: 80%;
    padding: 20px;
    text-align: center;">dddddddd</h1>
 
  </body>
  </html>
      <!-- end contact section -->
 

templates/about.html
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />


  <title>ECHRIDAR</title>

  <!-- slider stylesheet -->
  <link rel="stylesheet" type="text/css"
    href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css" />

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="static/css/bootstrap.css" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,700|Roboto:400,700&display=swap" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="static/css/style.css" rel="stylesheet" />
  <!-- responsive style -->
  <link href="static/css/responsive.css" rel="stylesheet" />
</head>

<body>
  <div class="hero_area">
        <!-- header section strats -->
        <header class="header_section">
          <div class="container-fluid">
            <nav class="navbar navbar-expand-lg custom_nav-container ">
              <a class="navbar-brand" href="{{ url_for('home') }}">
                <span>
                  ECHRIDAR
                </span>
              </a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
    
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="d-flex mx-auto flex-column flex-lg-row align-items-center">
                  <ul class="navbar-nav  ">
                    <li class="nav-item active">
                      <a class="nav-link" href="{{ url_for('home') }}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('about') }}"">About </a>
                    </li>
                    {% if not session.logged_in %}
                    <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('auth.login') }}">log in</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                      <a class="nav-link" href="{{ url_for('auth.logout') }}">log out</a>
                    </li>
                    {% endif %}
                    
              
                  </ul>
                </div>
                <div class="quote_btn-container  d-flex justify-content-center">
                  <a href="">
                    <img src="static/images/call.png" alt="">
                    CALL : +216 50677871
                  </a>
                  <a href="">
                    <span>
                      @
                    </span>
                    echridar1@gmail.com
                  </a>
                </div>
              </div>
            </nav>
          </div>
        </header>
        <!-- end header section -->
      </div>
    <!-- about section -->
<section class="about_section layout_padding">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <div class="detail-box">
                <div class="custom_heading-container">
                  <h2>
                    ABOUT            
                  </h2>
                  <hr>
                </div>
                <p>
                  ADD ABOUT SECTION! ADD ABOUT SECTION! ADD ABOUT SECTION!
                  ADD ABOUT SECTION! ADD ABOUT SECTION! ADD ABOUT SECTION!
                  ADD ABOUT SECTION!ADD ABOUT SECTION!
                </p>
                <!--<div>
                  <a href="">
                    Read More
                  </a>
                </div>-->
              </div>
            </div>
            <div class="col-md-6">
              <div class="img-box">
                <img src="static/images/about-img.png" alt="">
              </div>
            </div>
          </div>
      
        </div>
      </section>
      {% with messages = get_flashed_messages() %}
      {% if messages %}
        {% for message in messages %}
          <h3>{{ message }}</h3>
        {% endfor %}
      {% endif %}
    {% endwith %}
      
      <!-- end about section -->
</body>
</html>

templates/contact.html
{% extends "layout.html" %}
{% block content %}
        <!-- end header section --></div>
        <!-- contact section -->

<section class="contact_section layout_padding-bottom">
        <div class="container">
          <div class="row">
            <div class="custom_heading-container">
                <br><br><br><br><br><br>
              <h2>
                Contact Us
              </h2><hr>
            </div>
          </div>
          <div class="layout_padding-top layout_padding2-bottom">
            <div class="row">
              <div class="col-md-7">
                <form action="mailto:abdelhamid.zia@gmail.com" method="post" name="contact" enctype="text/plain">
                  <div class="contact_form-container">
                    <div>
                      <div>
                        <input type="text" placeholder="Name">
                      </div>
                      <div>
                        <input type="email" placeholder="Email">
                      </div>
                      <div>
                        <input type="text" placeholder="Phone Number">
                      </div>
                      <div class="">
                        <input type="text" placeholder="Message" class="message_input">
                      </div>
                      <div class="mt-5">
                        <button type="submit">
                          Send
                        </button>
                      </div>
                    </div>
      
                  </div>
      
                </form>
              </div>
                
      
      {% endblock content %}

      <!-- end contact section -->
    </body>
</html>

templates/index.html
{% extends "layout.html" %}
{% block content %}
<script type="text/javascript" src="static/js/jquery-3.4.1.min.js"></script>
<script type="text/javascript" src="static/js/bootstrap.js"></script>
    <section class=" slider_section position-relative">

      <div class="slider_bg-container">

      </div>
      <div class="slider-container">

        <div class="detail-box">
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="sr-only">Next</span>
          </a>
          <h1>
            PREDICT <br>
            REAL ESTATE <br>
            PRICE HERE
          </h1>
          <p>
            Add comment here !!!!!!!!
          </p>
          <div>
            <a href="{{ url_for('pred.predict') }}" class="slider-link">
              PREDICT
            </a>
          </div>
        </div>
        <div class="img-box">
          <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="static/images/slider-img3.jpg" alt="">
              </div>
              <div class="carousel-item">
                <img src="static/images/slider-img2.jpg" alt="">
              </div>
              <div class="carousel-item">
                <img src="static/images/slider-img1.jpg" alt="">
              </div>
            </div>

          </div>

        </div>
      </div>

    </section>
    <!-- end slider section -->
  </div>
<!-- about section -->


<!-- end about section -->
<!-- contact section -->
<!--
{% with messages = get_flashed_messages(category_filter=["success"]) %}
{% if messages %}
  {% for message in messages %}
  <div class="alert alert-success" role="alert">
    <p>{{ message  }}</p>
  </div>
  {% endfor %}
{% endif %}
{% endwith %}
-->          

{% endblock content %}

<!-- end contact section -->
<!-- info section -->
<section class="info_section layout_padding">
    <div class="container">
      <div class="info_social">
        <div>
          <a href="http://www.google.com">
            <img src="static/images/fb.png" alt="">
          </a>
        </div>
        <div>
          <a href="http://www.google.com">
            <img src="static/images/twitter.png" alt="">
          </a>
        </div>
        <div>
          <a href="http://www.google.com">
            <img src="static/images/linkedin.png" alt="">
          </a>
        </div>
        <div>
          <a href="http://www.google.com">
            <img src="static/images/insta.png" alt="">
          </a>
        </div>
      </div>
      <div>
        <p>
          ADD FOOTER 
        </p>
      </div>
    </div>
  </section>

  <!-- end info_section -->

  <!-- footer section -->
  <section class="container-fluid footer_section">
  
  </section>

  <!-- footer section -->



</body>

</html>

templates/layout.html
<!DOCTYPE html>
<html>

<head>

  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />


  <title>ECHRIDAR</title>

  <!-- slider stylesheet -->
  <link rel="stylesheet" type="text/css"
    href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css" />

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="static/css/bootstrap.css" />

  <link href="static/css/containerimage.css" rel="stylesheet" />


  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,700|Roboto:400,700&display=swap" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="static/css/style.css" rel="stylesheet" />
  <!-- responsive style -->
  <link href="static/css/responsive.css" rel="stylesheet" />

</head>

<body>
  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="{{ url_for('home') }}">
            <span>
              ECHRIDAR
            </span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="d-flex mx-auto flex-column flex-lg-row align-items-center">
              <ul class="navbar-nav  ">
                <li class="nav-item active">
                  <a class="nav-link" href="{{ url_for('home') }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('about') }}">About </a>
                </li>
                {% if not session.logged_in %}
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('auth.login',messages=request.path) }}">log in</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('auth.logout') }}">log out</a>
                </li>
                {% endif %}


              </ul>
            </div>
            <div class="quote_btn-container  d-flex justify-content-center">
              <a href="">
                <img src="static/images/call.png" alt="">
                CALL : +216 50677871
              </a>
              <a href="">
                <span>
                  @
                </span>
                echridar1@gmail.com
              </a>
            </div>
          </div>
        </nav>
      </div>
    </header>
  </div>

    <!-- end header section -->
  <!--</div>-->
  <!-- contact section -->


  {% block content %}{% endblock %}
  <br /> <br />
  <br /> <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />
  <br />


  <div class="contact_items">

    <a href="">
      <div class="item ">
        <div class="img-box box-2">

        </div>
        <div class="detail-box">
          <p>
            +216 50677871
          </p>
        </div>
      </div>
    </a>
    <a href="">
      <div class="item ">
        <div class="img-box box-3">

        </div>
        <div class="detail-box">
          <p>
            echridar1@gmail.com
          </p>
        </div>
      </div>
    </a>
    <a href="">
      <div class="item ">
        <div class="img-box box-1">

        </div>
        <div class="detail-box">
          <p>
            Add location
          </p>
        </div>
      </div>
    </a>

  </section>


  <!-- end contact section -->

templates/login.html
{% extends "layout.html" %}
{% block content %}
<section class="contact_section layout_padding-bottom">
        <div class="container">
          <div class="row">
            <div class="custom_heading-container">
                <br><br><br><br><br><br>
              <h2>
                Login
              </h2><hr>
            </div>
            
          </div>
          <div class="layout_padding-top layout_padding2-bottom">
            <div class="row">
              <div class="col-md-7">
                
        
                <form action="" method="POST">
                  
                {% with messages = get_flashed_messages(category_filter=["danger"]) %}
                {% if messages %}
                  {% for message in messages %}
                  <div class="alert alert-danger" role="alert">
                    <p>{{ message  }}</p>
                  </div>
                  {% endfor %}
                {% endif %}
              {% endwith %}
                  {{ form.hidden_tag() }}
                  <div class="contact_form-container">
                    <div>
                      <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                      <div class="mt-5">
                        <button type="submit">
                          Login
                        </button>
                       
                      </div>
                      </form>
                      <div>
                        <form action="{{ url_for('auth.register') }}">
                        <div class="mt-5">
                          <button type="submit">
                          Create an account
                        </button>
                      </div>
                      </form>
                      </div>
                    </div>
      
                  </div>
      
                
              </div>
{% endblock content %}
   </body>
</html>

templates/price.html
{% extends "layout.html" %}
{% block content %}
<section class="contact_section layout_padding-bottom">
    <div class="container">
        <div class="row">
            <div class="custom_heading-container">
                <br><br><br><br><br><br>
                <h2>
                    Predicted price
                </h2>
                <hr>
               
            
            </div>
        </div>

        <div class="bg-text">
            <h1 style="font-size:50px">The predicted price is :</h1>
            <h1 style="font-size:50px">{{price}}</h1>

        </div>




    
</div>




    {% endblock content %}
    </body>

    </html>

templates/registration.html
{% extends "layout.html" %}
{% block content %}

<section class="contact_section layout_padding-bottom">
        <div class="container">
          <div class="row">
            <div class="custom_heading-container">
                <br><br><br><br><br><br>
                <h2>
                Registration
                </h2><hr>
            </div>
          </div>
          <div class="layout_padding-top layout_padding2-bottom">
            <div class="row">
              <div class="col-md-7">
                <form action="{{ url_for('auth.register')}}" method="post">
                  {{ form.hidden_tag() }}
                  <div class="contact_form-container">
                    <div class="form-group">
                    {{ form.firstname.label(class="form-control-label") }}

                    {% if form.firstname.errors %}
                        {{ form.firstname(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.firstname.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.firstname(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                      <div class="form-group">
                    {{ form.lastname.label(class="form-control-label") }}

                    {% if form.lastname.errors %}
                        {{ form.lastname(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.lastname.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.lastname(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                      <div class="mt-5">
                        <button type="submit">
                          Register
                        </button>
                      </div>
                    </div>
      
                  </div>
      
                </form>
              </div>
                
     {% endblock content %}
 
      <!-- end contact section -->
    </body>
</html>